site_name: The Real-Timers Guide to the Computational Galaxy
docs_dir: .
site_dir: ../site
repo_url: https://github.com/absorensen/the-guide

theme:
  language: en
  name: material
  favicon: figures/nebula.png
  logo: figures/nebula.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox
  - same-dir
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email
      link: mailto:aboso@dtu.com
    - icon: fontawesome/brands/github
      link: https://github.com/absorensen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anders-bo-sorensen/

nav:
  - Home: README.md
  - Acknowledgements: acknowledgements.md
  - M0 - Introduction:
    - m0_introduction/README.md
    - S0 - Introduction to the Computing Landscape: m0_introduction/s0_intro_to_computing.md
    - S1 - Introduction to Rust: m0_introduction/s1_intro_to_rust.md
    - S2 - Basic Concepts in Rust: m0_introduction/s2_basic_concepts_in_rust.md
    - S3 - 3️⃣ Less Basic Concepts in Rust: m0_introduction/s3_less_basic_concepts_in_rust.md
    - S4 - 👨🏼‍💻 Exercises: m0_introduction/s4_exercises.md
  - M1 - Memory Hierarchies:
    - m1_memory_hierarchies/README.md
    - S0 - Soft Memory Hierarchies: m1_memory_hierarchies/s0_soft_memory_hierarchies.md
    - S1 - Computational Graphs: m1_memory_hierarchies/s1_computational_graphs.md
    - S2 - Introduction to GPU's: m1_memory_hierarchies/s2_intro_to_gpus.md
    - S3 - Immediate GPU Computation: m1_memory_hierarchies/s3_immediate_gpu_computation.md
    - S4 - Building a Computational Graph: m1_memory_hierarchies/s4_building_a_computational_graph.md
    - S5 - Computational Graph Compilers: m1_memory_hierarchies/s5_computational_graph_compilers.md
    - S6 - 👨🏼‍💻 Exercises: m1_memory_hierarchies/s6_exercises.md    
  - M2 - Concurrency:
    - m2_concurrency/README.md
    - S0 - Data Parallelism: m2_concurrency/s0_data_parallelism.md
    - S1 - Threads: m2_concurrency/s1_threads.md
    - S2 - Locks: m2_concurrency/s2_locks.md
    - S3 - Atomics: m2_concurrency/s3_atomics.md
    - S4 - Message Passing: m2_concurrency/s4_message_passing.md
    - S5 - Async: m2_concurrency/s5_async.md
    - S6 - 3️⃣ More GPU: m2_concurrency/s6_more_gpu.md
    - S7 - 3️⃣ Parallel Graphs: m2_concurrency/s7_parallel_graphs.md
    - S8 - 👨🏼‍💻 Exercises: m2_concurrency/s8_exercises.md
  - M3 - Types:
    - m3_types/README.md
    - S0 - Integers: m3_types/s0_integers.md
    - S1 - Floats: m3_types/s1_floats.md
    - S2 - Energy Efficiency: m3_types/s2_energy_efficiency.md
    - S3 - Bitwise Operations: m3_types/s3_bitwise_operations.md
    - S4 - 3️⃣ Bit Tricks: m3_types/s4_bit_tricks.md
    - S5 - 3️⃣ Compression: m3_types/s5_compression.md
    - S6 - 🧬3️⃣ Cooperative Matrices: m3_types/s6_cooperative_matrices.md
    - S7 - 👨🏼‍💻 Exercises: m3_types/s7_exercises.md
  - M4 - 3️⃣ Real-Time Systems:
    - m4_real_time_systems/README.md
    - S0 - Events and Interactions: m4_real_time_systems/s0_events_and_interactions.md
    - S1 - Graphical User Interfaces: m4_real_time_systems/s1_graphical_user_interfaces.md
    - S2 - Architecture and Design: m4_real_time_systems/s2_architecture_and_design.md
    - S3 - Branchless Programming: m4_real_time_systems/s3_branchless_programming.md
    - S4 - Logging: m4_real_time_systems/s4_logging.md
    - S5 - Bindings: m4_real_time_systems/s5_bindings.md
    - S6 - Tips and Tricks: m4_real_time_systems/s6_tips_and_tricks.md
    - S7 - 👨🏼‍💻 Exercises: m4_real_time_systems/s7_exercises.md
  - M5 - 3️⃣ Optimization:
    - m5_optimization/README.md
    - S0 - Timing and Printing: m5_optimization/s0_timing_and_printing.md
    - S1 - Profilers: m5_optimization/s1_profilers.md
    - S2 - 👨🏼‍💻 Exercises: m5_optimization/s2_exercises.md
  - M6 - 👨🏼‍💻🧬 Projects:
    - m6_projects/README.md
    - S0 - Project Ideas: m6_projects/s0_project_ideas.md