[package]
name = "sorting_functions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ultraviolet = { version = "0.9", features = [ "f64", "int" ] }
rayon = "1.5.3"
rand = "0.8.5"